# Configuration for the socksprox SOCKS5 server
# socksprox "follows" rfc 1928
# Run "socksprox -t" to test this config file

# Logging location
access-log = /var/log/socksprox.access
error-log = /var/log/socksprox.error

# Network port to listen on
listen-port = 1080

# ip addresses to listen on
# Add listen = <ip> as needed
# ipv4 or ipv6 allowed
listen = 0.0.0.0
listen = ::

# Let the client request domain names
# No will return "address type not supported" to the client
allow-domains = yes

# Commands allowed to be requested by clients
# Allow clients to initiate outbound connections
# No will return "command not supported" to the client
allow-connect = yes
allow-bind = no
allow-udp-associate = yes

# Maximum number of connections allowed at one time
max-connections = 1000

# Authentication methods
# There can be multiple allowed methods
method = no-auth
# method = username-password (not yet)
# method = gssapi (not yet)

# Block socks5 requests by address
# By default blocks private ranges and locahost
# block = ipv4 or ipv6 in cidr notation
block=192.168.0.0/16
block=172.16.0.0/12
block=10.0.0.0/8
block=100.64.0.0/10
block=127.0.0.0/8
block=0.0.0.0/32
block=fe80::/10
block=fc00::/8
block=::1/128
