# Configuration for the socksprox SOCKS5 server
# socksprox "follows" rfc 1928
# github.com/qkewq/socksprox
# Run "socksprox -t" to test this config file

# Logging location
# Access logs contain logs pertaining to network traffic
# Error logs contain logs pertaining to the server itself
access-log = /var/log/socksprox.access
error-log = /var/log/socksprox.error

# ip addresses and port to listen on
# Add listen = <ip>_<port> as needed
# ipv4 or ipv6 allowed
listen = 0.0.0.0_1080
listen = ::_1080

# Let the client request domain names
# Value of no will return "address type not supported" to the client
# Default no
allow-domains = yes

# Commands allowed to be requested by clients
# Allow clients to initiate outbound connections
# Value of no will return "command not supported" to the client
# All commands default to no
allow-connect = yes
allow-bind = no
allow-udp-associate = no

# The address to return to the client upon bind request
# The public address that the client can expect to reach the server with
# This argument is necessary if allow-bind is yes
#bind-advertise-address = <ipv4>
#bind-advertise-address = <ipv6>

# The address to actually listen on for bind requests
# Cannot be wildcard address
#bind-listen-address = <ipv4>
#bind-listen-address = <ipv6>

# The address to return to the client upon udp associat request
# The public address that the traffic will be relayed from
# This argument is necessary if allow-udp-associate is yes
#udp-advertise-address = <ipv4>
#udp-advertise-address = <ipv6>

# The address to actually listen on for udp associate requests
# Cannot be wildcard address
#udp-listen-address = <ipv4>
#udp-listen-address = <ipv6>

# Maximum number of connections allowed at one time
max-connections = 1000

# Authentication methods
# There can be multiple allowed methods
method = no-auth
# method = username-password (not yet)
# method = gssapi (not yet)

# Block socks5 requests by address
# By default blocks private ranges and localhost
# block = ipv4 or ipv6 in cidr notation
block=192.168.0.0/16
block=172.16.0.0/12
block=10.0.0.0/8
block=100.64.0.0/10
block=169.254.0.0/16
block=127.0.0.0/8
block=0.0.0.0/32
block=224.0.0.0/4
block=255.255.255.255/32
block=fe80::/10
block=fc00::/8
block=::1/128
block=::/128
block=ff00::/8
